### ISSUE TITLE
Net::ReadTimeout

### ISSUE THREAD

**Issue by jackal998** [jackal998/ChatGPT-for-line#20]
sidekiq_1   | 2023-03-23T15:00:38.919Z pid=1 tid=7ep WARN: Net::ReadTimeout: Net::ReadTimeout with #<Socket:(closed)>

**Comment by jackal998** [comment]
```
2023-03-28T16:04:35.775Z pid=1 tid=9jd class=OpenaiResponseJob jid=a040b317aff58951b090784c INFO: start
2023-03-28T16:05:36.001Z pid=1 tid=9jd class=OpenaiResponseJob jid=a040b317aff58951b090784c elapsed=60.226 INFO: fail
2023-03-28T16:05:36.001Z pid=1 tid=9jd WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"default","args":[{"user_id":"Ub84c18f927b589e3f0ed7dbe90bf44e4","user_input":"You will now act as a prompt generator for a generative AI called “Midjourney”. Midjourney AI generates images based on given prompts.\n\nI will provide a concept and you will provide the prompt for Midjourney AI.\n\nYou will never alter the structure and formatting outlined below in any way and obey the following guidelines:\n\nYou will not write the words “description” or use “:” in any form. Never place a comma between [ar] and [v].\n\nYou will write each prompt in one line without using return.\n\nStructure:\n\n[1] = [[實際描述]]\n[2] = a detailed description of [1] that will include very specific imagery details.\n[3] = with a detailed description describing the environment of the scene.\n[4] = with a detailed description describing the mood/feelings and atmosphere of the scene.\n[5] = A style, for example: photography, painting, illustration, sculpture, Artwork, paperwork, 3d and more). [1]\n[6] = A description of how [5] will be realized. (e.g. Photography (e.g. Macro, Fisheye Style, Portrait) with camera model and appropriate camera settings, Painting with detailed descriptions about the materials and working material used, rendering with engine settings, 
a digital Illustration, a woodburn art (and everything else that could be defined as an output type)\n[ar] = “–ar 16:9” if the image looks best horizontally, “–ar 9:16” if the image looks best vertically, “–ar 1:1” if the image looks best in a square. (Use exactly as written)\n[v] = If [5] looks best in a Japanese art style use, “--niji”. Otherwise use, “--v 4” (Use exactly as written)\nFormatting:\n\nWhat you write will be exactly as formatted in the structure below, including the “/” and “:” This is the prompt structure: “/imagine prompt: [1], [2], [3], [4], [5], [6], [ar] [v]”.\n\nThis is your task: You will generate 4 prompts for each concept [1], and each of your prompts will be a different approach in its description, environment, atmosphere, and realization.\n\nThe prompts you provide will be in English*.\n\nPlease pay attention:\n\nUse affirmative sentences and avoid using negative sentences.\nDescribe what you want clearly and avoid using abstract vocabulary.\nAvoid using overly detailed specifics and 
try to use singular nouns or specific numbers.\nAvoid using extended associative concepts and use more specific keywords.\nConcepts that can’t be real would not be described as “Real” or “realistic” or “photo” or a “photograph”. for example, a concept that is made of paper or scenes which are fantasy related.\nOne of the prompts you generate for each concept must be in a realistic photographic style. you should also choose a lens type and size for it. Don’t choose an artist for the realistic photography prompts.\nSeparate the different prompts with two new lines\n[VERY IMPORTANT] Provide a Traditional Chinese translation for every prompt.","reply_token":"247d21c43471482c87edb0cec6a893db"}],"class":"OpenaiResponseJob","jid":"a040b317aff58951b090784c","created_at":1680018649.6222491,"enqueued_at":1680019475.7747326,"error_message":"Net::ReadTimeout with #<Socket:(closed)>","error_class":"Net::ReadTimeout","failed_at":1680018709.8823311,"retry_count":4,"retried_at":1680019177.1863363}}
2023-03-28T16:05:36.001Z pid=1 tid=9jd WARN: Net::ReadTimeout: Net::ReadTimeout with #<Socket:(closed)>
2023-03-28T16:05:36.001Z pid=1 tid=9jd WARN: /app/vendor/bundle/ruby/3.1.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:229:in `rbuf_fill'
/app/vendor/bundle/ruby/3.1.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:199:in `readuntil'
/app/vendor/bundle/ruby/3.1.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:209:in `readline'
/usr/local/lib/ruby/3.1.0/net/http/response.rb:42:in `read_status_line'
/usr/local/lib/ruby/3.1.0/net/http/response.rb:31:in `read_new'
/usr/local/lib/ruby/3.1.0/net/http.rb:1575:in `block in transport_request'
/usr/local/lib/ruby/3.1.0/net/http.rb:1566:in `catch'
/usr/local/lib/ruby/3.1.0/net/http.rb:1566:in `transport_request'
/usr/local/lib/ruby/3.1.0/net/http.rb:1539:in `request'
/usr/local/lib/ruby/3.1.0/net/http.rb:1532:in `block in request'
/usr/local/lib/ruby/3.1.0/net/http.rb:966:in `start'
/usr/local/lib/ruby/3.1.0/net/http.rb:1530:in `request'
/app/vendor/bundle/ruby/3.1.0/gems/httparty-0.21.0/lib/httparty/request.rb:156:in `perform'
/app/vendor/bundle/ruby/3.1.0/gems/httparty-0.21.0/lib/httparty.rb:612:in `perform_request'
/app/vendor/bundle/ruby/3.1.0/gems/httparty-0.21.0/lib/httparty.rb:542:in `post'
/app/vendor/bundle/ruby/3.1.0/gems/httparty-0.21.0/lib/httparty.rb:649:in `post'
/app/vendor/bundle/ruby/3.1.0/gems/ruby-openai-3.4.0/lib/openai/client.rb:54:in `json_post'
/app/vendor/bundle/ruby/3.1.0/gems/ruby-openai-3.4.0/lib/openai/client.rb:11:in `chat'
/app/app/services/openai_response_generator.rb:7:in `execute'
/app/app/workers/openai_response_job.rb:27:in `get_response'
/app/app/workers/openai_response_job.rb:9:in `perform'
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:202:in `execute_job'
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:170:in `block (2 levels) in process'
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.8/lib/sidekiq/middleware/chain.rb:172:in `invoke'
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:169:in `block in process'
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.8/lib/sidekiq/job_retry.rb:113:in `local'
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.8/lib/sidekiq/rails.rb:14:in `block in call'
/app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4.2/lib/active_support/execution_wrapper.rb:92:in `wrap'
/app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4.2/lib/active_support/reloader.rb:72:in `block in wrap'
/app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4.2/lib/active_support/execution_wrapper.rb:92:in `wrap'
/app/vendor/bundle/ruby/3.1.0/gems/activesupport-7.0.4.2/lib/active_support/reloader.rb:71:in `wrap'
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.8/lib/sidekiq/rails.rb:13:in `call'
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:263:in `stats'
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.8/lib/sidekiq/job_logger.rb:13:in `call'
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.8/lib/sidekiq/job_retry.rb:80:in `global'
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:124:in `block in dispatch'
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.8/lib/sidekiq/job_logger.rb:39:in `prepare'
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:123:in `dispatch'
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:168:in `process'
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:78:in `process_one'
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:68:in `run'
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.8/lib/sidekiq/component.rb:8:in `watchdog'
/app/vendor/bundle/ruby/3.1.0/gems/sidekiq-6.5.8/lib/sidekiq/component.rb:17:in `block in safe_thread'
```
